'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Registration

 '''<summary>
 '''userHelpLabel control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents userHelpLabel As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''rpRoles control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents rpRoles As Global.System.Web.UI.WebControls.Repeater

 '''<summary>
 '''socialLoginControls control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents socialLoginControls As Global.System.Web.UI.WebControls.PlaceHolder

 '''<summary>
 '''captchaRow control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents captchaRow As Global.System.Web.UI.HtmlControls.HtmlGenericControl

 '''<summary>
 '''captchaLabel control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents captchaLabel As Global.System.Web.UI.UserControl

 '''<summary>
 '''ctlCaptcha control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ctlCaptcha As Global.DotNetNuke.UI.WebControls.CaptchaControl

 '''<summary>
 '''actionsRow control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents actionsRow As Global.System.Web.UI.HtmlControls.HtmlGenericControl

 '''<summary>
 '''registerButton control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents registerButton As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cancelButton control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cancelButton As Global.System.Web.UI.WebControls.LinkButton
End Class
